config/routes.rb
Rails.application.routes.draw do
  resources :author_lists
  resources :books do
    collection do
      get :search
    end
  end
  resources :authors
  resources :stillages
  resources :halls
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
    collection do
      post :create_by_admin
      get :new_by_admin
    end
  end

end

app/models/hall.rb
class Hall < ActiveRecord::Base
  has_many :stillages, dependent: :destroy
  
  validates :full_name, :short_name, presence: true
  validates :full_name, uniqueness: {scope: [:short_name]}
end

app/controllers/halls_controller.rb
class HallsController < ApplicationController
  before_action :set_hall, only: [:show, :edit, :update, :destroy]
  before_action :check_app_auth
  # GET /halls
  # GET /halls.json
  def index
    @halls = Hall.all
  end

  # GET /halls/1
  # GET /halls/1.json
  def show
  end

  # GET /halls/new
  def new
    @hall = Hall.new
  end

  # GET /halls/1/edit
  def edit
  end

  # POST /halls
  # POST /halls.json
  def create
    @hall = Hall.new(hall_params)

    respond_to do |format|
      if @hall.save
        format.html { redirect_to @hall, notice: 'Hall was successfully created.' }
        format.json { render :show, status: :created, location: @hall }
      else
        format.html { render :new }
        format.json { render json: @hall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /halls/1
  # PATCH/PUT /halls/1.json
  def update
    respond_to do |format|
      if @hall.update(hall_params)
        format.html { redirect_to @hall, notice: 'Hall was successfully updated.' }
        format.json { render :show, status: :ok, location: @hall }
      else
        format.html { render :edit }
        format.json { render json: @hall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /halls/1
  # DELETE /halls/1.json
  def destroy
    @hall.destroy
    respond_to do |format|
      format.html { redirect_to stillages_path(), notice: 'Hall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hall
      @hall = Hall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hall_params
      params.require(:hall).permit(:full_name, :short_name)
    end
end

app/helpers/halls_helper.rb
module HallsHelper
  def hall_options()
    Hall.all.map{|c| [c.full_name+'('+c.short_name+')', c.id ]}
  end
end

app/views/halls/_form.html.haml
= form_for @hall do |f|
  - if @hall.errors.any?
    #error_explanation
      %h2= "#{pluralize(@hall.errors.count, "error")} prohibited this hall from being saved:"
      %ul
        - @hall.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :full_name
    = f.text_field :full_name
  .field
    = f.label :short_name
    = f.text_field :short_name
  .actions
    = f.submit 'Save'

app/views/halls/edit.html.haml
%h1 Editing hall

= render 'form'

= link_to 'Show', @hall
\|
= link_to 'Back', halls_path

app/views/halls/index.html.haml
%h1= t('headers.halls.index')

%table
  %thead
    %tr
      %th= Hall.human_attribute_name(:name_full)
      %th= Hall.human_attribute_name(:name_short)
      %th
      %th
      %th

  %tbody
    - @halls.each do |hall|
      %tr
        %td= hall.name_full
        %td= hall.name_short
        %td= link_to 'Show', hall
        %td= link_to 'Edit', edit_hall_path(hall)
        %td= link_to 'Destroy', hall, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Hall', new_hall_path

app/views/halls/new.html.haml
%h1 New hall

= render 'form'

= link_to 'Back', halls_path

app/views/halls/show.html.haml
%p#notice= notice

%p
  %b= Hall.human_attribute_name(:full_name)
  = @hall.full_name
%p
  %b= Hall.human_attribute_name(:short_name)
  = @hall.short_name

= link_to 'Edit', edit_hall_path(@hall)
\|
= link_to 'Back', halls_path