config/routes.rb
Rails.application.routes.draw do
  resources :author_lists
  resources :books do
    collection do
      get :search
    end
  end
  resources :authors
  resources :stillages
  resources :halls
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
    collection do
      post :create_by_admin
      get :new_by_admin
    end
  end

end

app/models/author_list.rb
class AuthorList < ActiveRecord::Base
  belongs_to :author
  belongs_to :book
  
  validates :author, presence: true
  validates :author_id, uniqueness: {scope: [:book_id]}

  accepts_nested_attributes_for :author, allow_destroy: true
end

app/helpers/author_lists_helper.rb
module AuthorListsHelper
end

app/views/author_lists/_form.html.haml
= form_for @author_list do |f|
  - if @author_list.errors.any?
    #error_explanation
      %h2= "#{pluralize(@author_list.errors.count, "error")} prohibited this author_list from being saved:"
      %ul
        - @author_list.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :author
    = f.select(:author_id, options_for_select(Author.pluck('last_name, id'), f.object.author_id))
  .field
    = f.label :book
    = f.select(:book_id, options_for_select(Book.pluck('name, id'), f.object.book_id))
  .actions
    = f.submit 'Save'

app/views/author_lists/edit.html.haml
%h1 Editing author_list

= render 'form'

= link_to 'Show', @author_list
\|
= link_to 'Back', author_lists_path

app/views/author_lists/index.html.haml
%h1= t('headers.author_lists.index')

%table
  %thead
    %tr
      %th= AuthorList.human_attribute_name(:author)
      %th= AuthorList.human_attribute_name(:book)
      %th
      %th
      %th

  %tbody
    - @author_lists.each do |author_list|
      %tr
        %td= author_list.author.sname
        %td= author_list.book.name
        %td= link_to 'Show', author_list
        %td= link_to 'Edit', edit_author_list_path(author_list)
        %td= link_to 'Destroy', author_list, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Author list', new_author_list_path

app/views/author_lists/new.html.haml
%h1 New author_list

= render 'form'

= link_to 'Back', author_lists_path

app/views/author_lists/show.html.haml
%p#notice= notice

%p
  %b= AuthorList.human_attribute_name(:author)
  = @author_list.author.sname
%p
  %b= AuthorList.human_attribute_name(:book)
  = @author_list.book.name

= link_to 'Edit', edit_author_list_path(@author_list)
\|
= link_to 'Back', author_lists_path