config/routes.rb
Rails.application.routes.draw do
  resources :author_lists
  resources :books do
    collection do
      get :search
    end
  end
  resources :authors
  resources :stillages
  resources :halls
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
    collection do
      post :create_by_admin
      get :new_by_admin
    end
  end

end

app/models/stillage.rb
class Stillage < ActiveRecord::Base
  belongs_to :hall
  has_many :books, dependent: :destroy
  validates :index, :hall, presence: true

  accepts_nested_attributes_for :hall, allow_destroy: true
end

app/controllers/stillages_controller.rb
class StillagesController < ApplicationController
  before_action :set_stillage, only: [:show, :edit, :update, :destroy]
  skip_before_action :check_app_auth, only: [:index, :show]

  # GET /stillages
  # GET /stillages.json
  def index
    @stillages = Stillage.all
  end

  # GET /stillages/1
  # GET /stillages/1.json
  def show
  end

  # GET /stillages/new
  def new
    @stillage = Stillage.new
  end

  # GET /stillages/1/edit
  def edit
  end

  # POST /stillages
  # POST /stillages.json
  def create
    @stillage = Stillage.new(stillage_params)

    respond_to do |format|
      if @stillage.save
        format.html { redirect_to @stillage, notice: 'Stillage was successfully created.' }
        format.json { render :show, status: :created, location: @stillage }
      else
        format.html { render :new }
        format.json { render json: @stillage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stillages/1
  # PATCH/PUT /stillages/1.json
  def update
    respond_to do |format|
      if @stillage.update(stillage_params)
        format.html { redirect_to @stillage, notice: 'Stillage was successfully updated.' }
        format.json { render :show, status: :ok, location: @stillage }
      else
        format.html { render :edit }
        format.json { render json: @stillage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stillages/1
  # DELETE /stillages/1.json
  def destroy
    # будем удалять зал если удаляемый стеллаж последний 
    @stillage.hall.destroy if @stillage.hall.stillages.pluck(:index).size == 1
    @stillage.destroy
    respond_to do |format|
      format.html { redirect_to stillages_url, notice: 'Stillage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stillage
      @stillage = Stillage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stillage_params
      params.require(:stillage).permit(:index, :hall_id, 
        hall_attributes: [:full_name, :short_name, :id])
    end
end

app/helpers/stillages_helper.rb
module StillagesHelper
end

app/views/stillages/_form.html.haml
= form_for @stillage do |f|
  - if @stillage.errors.any?
    #error_explanation
      %h2= "#{pluralize(@stillage.errors.count, "error")} prohibited this stillage from being saved:"
      %ul
        - @stillage.errors.full_messages.each do |message|
          %li= message

  .row
    .col-md-6
      .form-group
        = f.label :hall
        = f.select(:hall_id, options_for_select(hall_options, f.object.hall_id), {include_blank: true}, {class: 'form-control hall_select', onchange: 'update_fields(this)'})
    .col-md-6
      .form-group
        = f.label :index
        = f.number_field :index, class: 'form-control'
  .row 
    = f.fields_for :hall, f.object.hall || f.object.build_hall do |hall|
      = hall.hidden_field :id, class: 'hall_id'
      .col-md-6
        .form-group
          = hall.label :full_name
          = hall.text_field :full_name, class: 'form-control full_name'
          = hall.error_messages_for(:full_name)
      .col-md-6
        .form-group
          = hall.label :short_name
          = hall.text_field :short_name, class: 'form-control short_name'
          = hall.error_messages_for(:short_name)
  - if params[:action] == 'edit'
    - if !f.object.new_record?
      = link_to @stillage.hall,
      :method => :delete,
      :data => { :confirm => t('buttons.confirm.hall') },
      class: 'btn btn-danger' do
        = fa_icon :times
        = t('buttons.destroy')
  .form-actions.bottom20
    = f.submit nil, class: 'btn btn-primary'

app/views/stillages/edit.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.stillages.edit')
  %li
    = link_to (@stillage.index.to_s() + ' в ' + @stillage.hall.full_name + ' (' + @stillage.hall.short_name + ')'), @stillage
  %li
    = link_to t('headers.stillages.index'), stillages_path()
  %li
    Библиотека

.page-header
  %h1= t('headers.stillages.edit')

= render 'form'

app/views/stillages/index.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.stillages.index')
  %li
    Библиотека

.page-header
  %h1= t('headers.stillages.index')

%table.table.table-hover.table-striped
  %caption
    = link_to new_stillage_path, class: 'btn btn-success' do
      = fa_icon :plus
      = t('buttons.new.stillage') 
  %thead
    %tr
      %th= Stillage.human_attribute_name(:index)
      %th= Stillage.human_attribute_name(:hall)
      %th
      %th
      %th

  %tbody
    - @stillages.each do |stillage|
      %tr
        %td.center= stillage.index
        %td.center= stillage.hall.full_name + ' (' + stillage.hall.short_name + ')'
        %td.right
          = link_to stillage, class: 'btn btn-success'  do
            = fa_icon :eye
        %td.right
          = link_to edit_stillage_path(stillage), class: 'btn btn-info' do
            = fa_icon :edit
        %td.right
          = link_to stillage, :method => :delete, 
          :data => { :confirm => t('buttons.confirm.stillage') }, 
          class: 'btn btn-danger' do
            = fa_icon :times
%br

%br

app/views/stillages/new.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.stillages.new')
  %li
    = link_to t('headers.stillages.index'), stillages_path()
  %li
    Библиотека

.page-header
  %h1= t('headers.stillages.new')

= render 'form'

app/views/stillages/show.html.haml
=breadcrumb_tag do
  %li.active
    = @stillage.index.to_s() + ' в ' + @stillage.hall.full_name + ' (' + @stillage.hall.short_name + ')'
  %li
    = link_to t('headers.stillages.index'), stillages_path()
  %li
    Библиотека

.page-header
  %h1= @stillage.index.to_s() + ' в ' + @stillage.hall.full_name + ' (' + @stillage.hall.short_name + ')'

%p
  %b= Stillage.human_attribute_name(:index)
  = @stillage.index
%p
  %b= Stillage.human_attribute_name(:hall)
  = @stillage.hall.full_name + ' (' + @stillage.hall.short_name + ')'